export const GRADIENTS = [
    "aqua_splash",
    "vicious_stance",
    "young_passion",
    "morning_salad",
    "mind_crawl",
    "angel_care",
    "juicy_cake",
    "sun_veggie",
    "grass_shampoo",
    "flying_lemon",
    "colorful_peach",
    "light_blue",
    "dense_water",
    "supreme_sky",
    "child_care",
    "morning_eggplant",
    "apple_dew",
    "peach_stone",
    "slate",
    "vermillion_sand",
    "desert_glow",
    "bruised_desert",
    "bleached_blue",
    "decent",
    "royal",
    "shades_50",
    "mauve",
    "summer_orange",
    "morning_dew",
    "scorched_desert",
    "dark_forest",
    "everlasting_sky",
    "blessing",
    "soft_cherish",
    "perfect_white",
    "strict_november",
    "salt_mountain",
] as const;

export type GradientType = (typeof GRADIENTS)[number];
